# Generated by Django 5.1 on 2024-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='added_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
