# Generated by Django 5.1 on 2024-08-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_image_book_tag_alter_book_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_image',
            new_name='image',
        ),
    ]
