# Generated by Django 5.1 on 2024-08-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_book_image_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_date',
            new_name='published_date',
        ),
    ]
