# Generated by Django 5.1 on 2024-08-21 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
